# dark powered

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'BufRead'

## neosnippet
[[plugins]]
repo = 'Shougo/neosnippet'
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# CVS
[[plugins]]
repo = 'mhinz/vim-signify'
on_event = 'BufRead'
hook_add = '''
	set updatetime=100
'''

[[plugins]]
repo = "tpope/vim-fugitive"
on_event = 'VimEnter'

[[plugins]]
repo = "rhysd/git-messenger.vim"
on_cmd = "GitMessenger"
on_map = "<Plug>(git-messenger"

# debug
[[plugins]]
repo = 'sakhnik/nvim-gdb'
on_ft = ['c', 'cpp']

[[plugins]]
repo = "preservim/tagbar"
hook_add = '''
	nnoremap <silent> <Leader>t :TagbarToggle<CR>
'''

# language
[[plugins]]
repo = 'rust-lang/rust.vim'
depends = ['tagbar']
on_ft = ['rust']
hook_add = '''
	let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'ziglang/zig.vim'
on_ft = ['zig']

[[plugins]]
repo = 'zenlang/zen.vim'
on_ft = ['zen']

[[plugins]]
repo = 'zah/nim.vim'
on_ft = ['nim']

# utility

#[[plugins]]
#repo = 'editorconfig/editorconfig-vim'
#on_ft = ['c']
#hook_add = '''
#	let g:EditorConfig_exclude_patterns = ['fugitive://.*']
#'''

## table
#[[plugins]]
#repo = 'mattn/vim-maketable'
#on_ft = ['markdown']

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown']

## preview
[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_add = '''
  let g:previm_open_cmd = "firefox"
'''
